### ISSUE TITLE
Could you modify LICENSE file to be detected correctly by go.dev?

### ISSUE THREAD

**Issue by hnakamur** [dgryski/go-metro#5]
Hi, thanks for porting and sharing MetroHash Go implementation!

Currently, the document for this package is not displayed at go.dev since the license is not detected correctly.
https://pkg.go.dev/github.com/dgryski/go-metro?tab=overview

Could you modify LICENSE file to be detected correctly by go.dev?

**Comment by dgryski** [comment]
Sorry, didn't this this issue.  Yes, I'll fix the license.

**Comment by dgryski** [comment]
The license appears to be detected correctly as MIT: https://pkg.go.dev/github.com/dgryski/go-metro?tab=licenses
